# Generated by Django 4.2.6 on 2023-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_number",
                    models.CharField(max_length=50, verbose_name="Трек номер"),
                ),
                (
                    "fullname",
                    models.CharField(max_length=100, verbose_name="Полное имя"),
                ),
                (
                    "passport_series",
                    models.CharField(max_length=3, verbose_name="Серия пасопрта"),
                ),
                (
                    "passport_number",
                    models.CharField(max_length=10, verbose_name="Номер паспорта"),
                ),
                ("pinfl", models.CharField(max_length=50, verbose_name="ПИНФЛ")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
